INSERT INTO services (id, title) VALUES (123, 'House Cleaners');
INSERT INTO services (id, title) VALUES (234, 'Interior Painters');
INSERT INTO services (id, title) VALUES (345, 'Handymen');
INSERT INTO services (id, title) VALUES (456, 'Photographers');
INSERT INTO services (id, title) VALUES (567, 'Makeup Artists');
INSERT INTO services (id, title) VALUES (678, 'Dog Groomers');
INSERT INTO services (id, title) VALUES (789, 'Dog Trainers');
INSERT INTO services (id, title) VALUES (890, 'Pet Sitters');
INSERT INTO services (id, title) VALUES (321, 'Math Tutoring');
INSERT INTO services (id, title) VALUES (432, 'Piano Lessons');
INSERT INTO services (id, title) VALUES (543, 'Personal Training');
